### ISSUE TITLE
Add support for Carthage

### ISSUE THREAD

**Issue by StefanWittwer** [robertherdzik/RHPlaceholder#13]
Hi there, great job on the library, it is quite neat and useful – however I ran into a problem when trying to install it via Carthage.

Here's the console output:
```
$ carthage update --platform iOS
*** Cloning RHPlaceholder
*** Checking out RHPlaceholder at "0.0.1"
*** xcodebuild output can be found in /(…)
*** Skipped building RHPlaceholder due to the error:
Dependency "RHPlaceholder" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/robertherdzik/RHPlaceholder/issues/new
```

Possibly the scheme [isn't marked as shared?](https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework), which is a requirement for Carthage to build the framework.

### Marking an Xcode project scheme as shared
![image](https://user-images.githubusercontent.com/5149339/43686207-2002f3ae-98c2-11e8-91a5-fd940791e9ec.png)
_Image from [Xcode Documentation](https://developer.apple.com/library/archive/documentation/IDEs/Conceptual/xcode_guide-continuous_integration/ConfigureBots.html#//apple_ref/doc/uid/TP40013292-CH9-SW3)_

It might be that, but I'm not sure – For now, I'll just add the dependency manually, but it is possible that other people might run into this issue. Other than that, great job again! 👍🏻

**Comment by robertherdzik** [comment]
Hi, thanks :) I'm going to work on it ;)
in touch!

**Comment by robertherdzik** [comment]
@StefanWittwer please check latest release and tell me whether everything works :)

**Comment by StefanWittwer** [comment]
That was fast! :)
I checked it again with 0.0.3 and it works like a charm now, thanks a lot!
Cheers!
