### ISSUE TITLE
add in UItableview

### ISSUE THREAD

**Issue by PrakashMaharjan** [robertherdzik/RHPlaceholder#18]
How to add this in custom UITableViewCell cell or collection view cell?

**Comment by robertherdzik** [comment]
Hi, you need to create placeholders cells for time in which you will wait for response (how many you want), and attach Placeholders to theirs UI elements, then after you receive final data you should reload them with correct list of cells. 
Is the quickest solution.

Let me know whether I answered to your question.

**Comment by robertherdzik** [comment]
due to lack of response
